### ISSUE TITLE
Remove csv from requirements

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/predictKAM#2]
I had to remove csv from requirements.txt to make the install work (I use a python 3.7 env).
I got this otherwise:

```
ERROR: Could not find a version that satisfies the requirement csv
ERROR: No matching distribution found for csv
```

This is probably related to this: https://stackoverflow.com/questions/41061824/install-csv-package-in-pycharm

**Comment by suhlrich** [comment]
great. I'll remove that. Thanks!
